/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface ClinicalNote {
  author_id: number | null;
  content: string;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  is_deleted: Generated<boolean>;
  original_id: Int8 | null;
  public_id: Generated<string>;
  referral_id: number;
  session_date: Generated<Timestamp>;
  updated_at: Generated<Timestamp>;
}

export interface CreditCard {
  card_number_encrypted: string;
  created_at: Generated<Timestamp>;
  cvv_encrypted: string | null;
  expiry_encrypted: string;
  id: Generated<number>;
  referral_id: number;
  updated_at: Generated<Timestamp>;
}

export interface File {
  created_at: Generated<Timestamp>;
  file_data: Buffer;
  file_name: string;
  file_size: Int8;
  id: Generated<number>;
  is_deleted: Generated<boolean>;
  mime_type: string;
  public_id: Generated<string>;
  referral_id: number;
  updated_at: Generated<Timestamp>;
  uploaded_by: number | null;
}

export interface OriginalClients {
  address: string | null;
  archived: Generated<boolean | null>;
  clinical_notes: string | null;
  closed: Generated<boolean | null>;
  deleted: Generated<boolean>;
  dob: Timestamp | null;
  email: string | null;
  file_closed: Timestamp | null;
  file_opened: Timestamp | null;
  first_name: Generated<string>;
  id: Generated<number>;
  last_name: Generated<string>;
  last_updated: Generated<Timestamp>;
  notes: string | null;
  parents: string | null;
  phone: string | null;
  phone_2: string | null;
  referral_date: Timestamp | null;
  referral_type: string;
  referrer_email: Generated<string | null>;
  referrer_name: string;
  referrer_relationship: string | null;
  therapy: Generated<string | null>;
}

export interface OriginalClinicalNote {
  client_id: number;
  clinical_note: string;
  created: Timestamp;
  deleted: Generated<boolean | null>;
  id: Generated<Int8>;
  session_date: Timestamp | null;
  updated: Generated<Timestamp>;
  version: Int8 | null;
}

export interface Referral {
  address_1: string | null;
  address_2: string | null;
  archived_at: Timestamp | null;
  assigned_to: number | null;
  city: string | null;
  closed_at: Timestamp | null;
  country: string | null;
  created_at: Generated<Timestamp>;
  date_of_birth: Timestamp | null;
  email: string | null;
  first_name: string;
  gender: string | null;
  id: Generated<number>;
  is_deleted: Generated<boolean>;
  last_name: string;
  method_of_payment: string | null;
  opened_at: Timestamp | null;
  original_id: number | null;
  parents_guardians: string | null;
  postal_zip: string | null;
  presenting_issues: string | null;
  primary_telephone: string;
  province_state: string | null;
  public_id: Generated<string>;
  referral_type: string;
  referred_at: Generated<Timestamp | null>;
  referrer_email: string | null;
  referrer_name: string | null;
  referrer_prefers_contact: boolean | null;
  referrer_relationship: string | null;
  requested_service: string;
  secondary_telephone: string | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface ReferralEmail {
  bounce_description: string | null;
  bounce_type: string | null;
  bounced_at: Timestamp | null;
  click_location: string | null;
  clicked_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  delivered_at: Timestamp | null;
  details: string | null;
  email_content: string | null;
  file_id: number | null;
  first_open: boolean | null;
  from_email: string;
  id: Generated<number>;
  message_id: string | null;
  metadata: Json | null;
  opened_at: Timestamp | null;
  original_link: string | null;
  platform: string | null;
  recipient_email: string;
  record_type: string | null;
  referral_id: number;
  spam_complaint_at: Timestamp | null;
  status: Generated<string>;
  subject: string | null;
  tag: string | null;
  updated_at: Generated<Timestamp>;
  user_agent: string | null;
  webhook_data: Json | null;
}

export interface User {
  created_at: Generated<Timestamp>;
  disabled: Generated<boolean>;
  email: string | null;
  failed_login_attempts: Generated<number>;
  id: Generated<number>;
  is_deleted: Generated<boolean>;
  last_login_at: Timestamp | null;
  locked: Generated<boolean>;
  name: string | null;
  password: string;
  public_id: Generated<string>;
  updated_at: Generated<Timestamp>;
  username: string;
}

export interface UserRole {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  role: string;
  updated_at: Generated<Timestamp>;
  user_id: number;
}

export interface DB {
  clinical_note: ClinicalNote;
  credit_card: CreditCard;
  file: File;
  original_clients: OriginalClients;
  original_clinical_note: OriginalClinicalNote;
  referral: Referral;
  referral_email: ReferralEmail;
  user: User;
  user_role: UserRole;
}
