/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface ClinicalNote {
  author_id: string | null;
  content: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_deleted: Generated<boolean>;
  session_date: Timestamp;
  referral_id: string;
  updated_at: Generated<Timestamp>;
}

export interface File {
  created_at: Generated<Timestamp>;
  file_data: Buffer;
  file_name: string;
  file_size: Int8;
  id: Generated<string>;
  is_deleted: Generated<boolean>;
  mime_type: string;
  referral_id: string;
  updated_at: Generated<Timestamp>;
  uploaded_by: string | null;
}

export interface Referral {
  closed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  date_of_birth: Timestamp;
  email: string | null;
  first_name: string;
  id: Generated<string>;
  is_deleted: Generated<boolean>;
  last_name: string;
  mailing_address: string | null;
  method_of_payment: string | null;
  opened_at: Timestamp | null;
  parents_guardians: string | null;
  presenting_issues: string | null;
  primary_telephone: string;
  referral_type: string;
  referred_at: Generated<Timestamp | null>;
  referrer_email: string | null;
  referrer_name: string | null;
  referrer_prefers_contact: boolean | null;
  referrer_relationship: string | null;
  requested_service: string;
  secondary_telephone: string | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface User {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_deleted: Generated<boolean>;
  last_login_at: Timestamp | null;
  password: string;
  updated_at: Generated<Timestamp>;
  username: string;
}

export interface DB {
  clinical_note: ClinicalNote;
  file: File;
  referral: Referral;
  user: User;
}
