export interface Referral {
  id: string;
  first_name: string;
  last_name: string;
  date_of_birth: string | null;
  age: string | null;
  age_at_referral: string | null;
  gender: string | null;
  parents_guardians: string | null;
  primary_telephone: string;
  secondary_telephone: string | null;
  email: string | null;
  address_1: string | null;
  address_2: string | null;
  city: string | null;
  province_state: string | null;
  country: string | null;
  postal_zip: string | null;
  referrer_name: string | null;
  referrer_relationship: string | null;
  referrer_email: string | null;
  requested_service: string;
  presenting_issues: string | null;
  method_of_payment: string | null;
  referrer_prefers_contact: boolean | null;
  referral_type: 'professional' | 'self';
  status: 'unassigned' | 'new' | 'opened' | 'closed' | 'archived';
  assigned_to: string | null;
  assigned_to_name: string | null;
  opened_at: string | null;
  closed_at: string | null;
  archived_at: string | null;
  referred_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface NewReferral {
  first_name: string;
  last_name: string;
  date_of_birth: string | Date | null;
  referred_at?: string | Date;
  gender?: string;
  parents_guardians?: string;
  primary_telephone: string;
  secondary_telephone?: string;
  email?: string;
  address_1?: string;
  address_2?: string;
  city?: string;
  province_state?: string;
  country?: string;
  postal_zip?: string;
  referrer_name?: string;
  referrer_relationship?: string;
  referrer_email?: string;
  requested_service: string;
  presenting_issues?: string;
  method_of_payment?: string;
  referrer_prefers_contact?: boolean;
  referral_type: 'professional' | 'self';
}
